### PR TITLE
Update task.md

### PR DESCRIPTION
**Pull request by toomeykh**
The page says that the stemcell download is optional but doesn't say how to enable/disable.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@toomeykh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/docs-platform-automation&pullRequestId=19)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/docs-platform-automation&pullRequestId=19) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@toomeykh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/docs-platform-automation&pullRequestId=19)!

**Comment by anEXPer** [comment]
Thanks for this PR!

We'll probably take and then modify it. We appreciate the need to call attention to and describe this behavior, but the list of valid IaaS names and the description of how it works aren't quite right.

I'd expect to see us get to this in the next day or two.

**Comment by anEXPer** [comment]
@toomeykh we pulled this in and reworked it a bit. Let us know what you think; it should be live on our [staging](https://docs-pcf-staging.cfapps.io/platform-automation/v3.0/reference/task.html#download-product) environment shortly.

**Comment by toomeykh** [comment]
@anEXPer That's a definite improvement over my attempt.  Great catch on the "if it's a .pivotal file", I totally missed that.
Thanks for the help with my first public commit!

**Pull request merged**
