### PR TITLE
Let's retire trusty stemcells

### PR DESCRIPTION
**Pull request by jghiloni**
Trusty had a good run, but it should be able to go golfing with friends and not have to do work in our docs. Also fixed a typo I noticed.

### CODE REVIEW

**Comment by kcboyle** [comment]
sounds good to me

**Comment by kcboyle** [comment]
how far back would we want this to go? 5.0 forward, or back to 4.4/4.3?

**Comment by jghiloni** [comment]
I think probably 5.0 and beyond, but am ambivalent beyond that

**Comment by kcboyle** [comment]
Cool. I'm not going to backport this yet! Thank you!

**Pull request merged**
